

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_matrix_sdk_ffi(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackmatrix_sdk_ffi(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackmatrix_sdk_ffi(void*, int8_t);

void uniffi_matrix_sdk_ffi_fn_free_mediasource(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_constructor_mediasource_from_json(
	RustBuffer json,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_mediasource_to_json(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_mediasource_url(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roommessageeventcontentwithoutrelation(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roommessageeventcontentwithoutrelation_with_mentions(
	void* ptr,
	RustBuffer mentions,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_authenticationservice(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_constructor_authenticationservice_new(
	RustBuffer base_path,
	RustBuffer passphrase,
	RustBuffer user_agent,
	RustBuffer oidc_configuration,
	RustBuffer custom_sliding_sync_proxy,
	RustBuffer session_delegate,
	RustBuffer cross_process_refresh_lock_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_authenticationservice_configure_homeserver(
	void* ptr,
	RustBuffer server_name_or_homeserver_url,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_authenticationservice_homeserver_details(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_authenticationservice_login(
	void* ptr,
	RustBuffer username,
	RustBuffer password,
	RustBuffer initial_device_name,
	RustBuffer device_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_authenticationservice_login_with_oidc_callback(
	void* ptr,
	void* authentication_data,
	RustBuffer callback_url,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_authenticationservice_url_for_oidc_login(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_client(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_account_data(
	void* ptr,
	RustBuffer event_type,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_account_url(
	void* ptr,
	RustBuffer action,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_avatar_url(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_cached_avatar_url(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_create_room(
	void* ptr,
	RustBuffer request,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_device_id(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_display_name(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_client_encryption(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_get_dm_room(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_get_media_content(
	void* ptr,
	void* media_source,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_client_get_media_file(
	void* ptr,
	void* media_source,
	RustBuffer body,
	RustBuffer mime_type,
	int8_t use_cache,
	RustBuffer temp_dir,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_get_media_thumbnail(
	void* ptr,
	void* media_source,
	uint64_t width,
	uint64_t height,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_client_get_notification_settings(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_get_profile(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_client_get_session_verification_controller(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_homeserver(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_ignore_user(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_login(
	void* ptr,
	RustBuffer username,
	RustBuffer password,
	RustBuffer initial_device_name,
	RustBuffer device_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_logout(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_client_notification_client(
	void* ptr,
	RustBuffer process_setup,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_remove_avatar(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_restore_session(
	void* ptr,
	RustBuffer session,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_rooms(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_search_users(
	void* ptr,
	RustBuffer search_term,
	uint64_t limit,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_session(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_set_account_data(
	void* ptr,
	RustBuffer event_type,
	RustBuffer content,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_set_delegate(
	void* ptr,
	RustBuffer delegate,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_set_display_name(
	void* ptr,
	RustBuffer name,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_set_pusher(
	void* ptr,
	RustBuffer identifiers,
	RustBuffer kind,
	RustBuffer app_display_name,
	RustBuffer device_display_name,
	RustBuffer profile_tag,
	RustBuffer lang,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_client_sync_service(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_unignore_user(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_client_upload_avatar(
	void* ptr,
	RustBuffer mime_type,
	RustBuffer data,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_upload_media(
	void* ptr,
	RustBuffer mime_type,
	RustBuffer data,
	RustBuffer progress_watcher,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_client_user_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_clientbuilder(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_constructor_clientbuilder_new(
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_base_path(
	void* ptr,
	RustBuffer path,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_build(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_disable_automatic_token_refresh(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_disable_ssl_verification(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_enable_cross_process_refresh_lock(
	void* ptr,
	RustBuffer process_id,
	uint64_t session_delegate,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_homeserver_url(
	void* ptr,
	RustBuffer url,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_passphrase(
	void* ptr,
	RustBuffer passphrase,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_proxy(
	void* ptr,
	RustBuffer url,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_server_name(
	void* ptr,
	RustBuffer server_name,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_server_versions(
	void* ptr,
	RustBuffer versions,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_set_session_delegate(
	void* ptr,
	uint64_t session_delegate,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_sliding_sync_proxy(
	void* ptr,
	RustBuffer sliding_sync_proxy,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_user_agent(
	void* ptr,
	RustBuffer user_agent,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_clientbuilder_username(
	void* ptr,
	RustBuffer username,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_encryption(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_backup_exists_on_server(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_encryption_backup_state(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_backup_state_listener(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_disable_recovery(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_enable_backups(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_enable_recovery(
	void* ptr,
	int8_t wait_for_backups_to_upload,
	uint64_t progress_listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_fix_recovery_issues(
	void* ptr,
	RustBuffer recovery_key,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_is_last_device(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_recover_and_reset(
	void* ptr,
	RustBuffer old_recovery_key,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_encryption_recovery_state(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_recovery_state_listener(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_reset_recovery_key(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_encryption_wait_for_backup_upload_steady_state(
	void* ptr,
	RustBuffer progress_listener,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_eventtimelineitem(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_can_be_replied_to(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_content(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_debug_info(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_event_id(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_is_editable(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_is_local(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_is_own(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_is_remote(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_local_send_state(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_origin(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_reactions(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_read_receipts(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_sender(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_sender_profile(
	void* ptr,
	RustCallStatus* out_status
);

uint64_t uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_timestamp(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_eventtimelineitem_transaction_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_homeserverlogindetails(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_homeserverlogindetails_supports_oidc_login(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_homeserverlogindetails_supports_password_login(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_homeserverlogindetails_url(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_mediafilehandle(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_mediafilehandle_path(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_mediafilehandle_persist(
	void* ptr,
	RustBuffer path,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_message(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_message_body(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_message_in_reply_to(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_message_is_edited(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_message_is_threaded(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_message_msgtype(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_notificationclient(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_notificationclient_get_notification(
	void* ptr,
	RustBuffer room_id,
	RustBuffer event_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_notificationclientbuilder(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationclientbuilder_filter_by_push_rules(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationclientbuilder_finish(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_notificationsettings(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_can_homeserver_push_encrypted_event_to_device(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_contains_keywords_rules(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_get_default_room_notification_mode(
	void* ptr,
	int8_t is_encrypted,
	int8_t is_one_to_one,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_get_room_notification_settings(
	void* ptr,
	RustBuffer room_id,
	int8_t is_encrypted,
	int8_t is_one_to_one,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_get_rooms_with_user_defined_rules(
	void* ptr,
	RustBuffer enabled,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_get_user_defined_room_notification_mode(
	void* ptr,
	RustBuffer room_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_is_call_enabled(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_is_room_mention_enabled(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_is_user_mention_enabled(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_restore_default_room_notification_mode(
	void* ptr,
	RustBuffer room_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_set_call_enabled(
	void* ptr,
	int8_t enabled,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_set_default_room_notification_mode(
	void* ptr,
	int8_t is_encrypted,
	int8_t is_one_to_one,
	RustBuffer mode,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_notificationsettings_set_delegate(
	void* ptr,
	RustBuffer delegate,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_set_room_mention_enabled(
	void* ptr,
	int8_t enabled,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_set_room_notification_mode(
	void* ptr,
	RustBuffer room_id,
	RustBuffer mode,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_set_user_mention_enabled(
	void* ptr,
	int8_t enabled,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_notificationsettings_unmute_room(
	void* ptr,
	RustBuffer room_id,
	int8_t is_encrypted,
	int8_t is_one_to_one,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_oidcauthenticationdata(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_oidcauthenticationdata_login_url(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_room(
	void* ptr,
	RustCallStatus* out_status
);

uint64_t uniffi_matrix_sdk_ffi_fn_method_room_active_members_count(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_active_room_call_participants(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_add_timeline_listener(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_alternative_aliases(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_avatar_url(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_ban(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_invite(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_kick(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_redact(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_send_message(
	void* ptr,
	RustBuffer user_id,
	RustBuffer message,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_send_state(
	void* ptr,
	RustBuffer user_id,
	RustBuffer state_event,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_can_user_trigger_room_notification(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_cancel_send(
	void* ptr,
	RustBuffer txn_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_canonical_alias(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_create_poll(
	void* ptr,
	RustBuffer question,
	RustBuffer answers,
	uint8_t max_selections,
	RustBuffer poll_kind,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_display_name(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_edit(
	void* ptr,
	void* new_content,
	void* edit_item,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_edit_poll(
	void* ptr,
	RustBuffer question,
	RustBuffer answers,
	uint8_t max_selections,
	RustBuffer poll_kind,
	void* edit_item,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_end_poll(
	void* ptr,
	RustBuffer poll_start_id,
	RustBuffer text,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_fetch_details_for_event(
	void* ptr,
	RustBuffer event_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_fetch_members(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_get_event_timeline_item_by_event_id(
	void* ptr,
	RustBuffer event_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_get_timeline_event_content_by_event_id(
	void* ptr,
	RustBuffer event_id,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_room_has_active_room_call(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_ignore_user(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_invite_user_by_id(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

uint64_t uniffi_matrix_sdk_ffi_fn_method_room_invited_members_count(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_inviter(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_room_is_direct(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_room_is_encrypted(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_room_is_public(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_room_is_space(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_room_is_tombstoned(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_join(
	void* ptr,
	RustCallStatus* out_status
);

uint64_t uniffi_matrix_sdk_ffi_fn_method_room_joined_members_count(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_leave(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_member(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_member_avatar_url(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_member_display_name(
	void* ptr,
	RustBuffer user_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_members(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_membership(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_name(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_own_user_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_paginate_backwards(
	void* ptr,
	RustBuffer opts,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_redact(
	void* ptr,
	RustBuffer event_id,
	RustBuffer reason,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_remove_avatar(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_remove_timeline(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_report_content(
	void* ptr,
	RustBuffer event_id,
	RustBuffer score,
	RustBuffer reason,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_retry_decryption(
	void* ptr,
	RustBuffer session_ids,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_retry_send(
	void* ptr,
	RustBuffer txn_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_room_info(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_send(
	void* ptr,
	void* msg,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_send_audio(
	void* ptr,
	RustBuffer url,
	RustBuffer audio_info,
	RustBuffer progress_watcher,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_send_file(
	void* ptr,
	RustBuffer url,
	RustBuffer file_info,
	RustBuffer progress_watcher,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_send_image(
	void* ptr,
	RustBuffer url,
	RustBuffer thumbnail_url,
	RustBuffer image_info,
	RustBuffer progress_watcher,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_send_location(
	void* ptr,
	RustBuffer body,
	RustBuffer geo_uri,
	RustBuffer description,
	RustBuffer zoom_level,
	RustBuffer asset_type,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_send_poll_response(
	void* ptr,
	RustBuffer poll_start_id,
	RustBuffer answers,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_send_read_receipt(
	void* ptr,
	RustBuffer event_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_send_reply(
	void* ptr,
	void* msg,
	void* reply_item,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_send_video(
	void* ptr,
	RustBuffer url,
	RustBuffer thumbnail_url,
	RustBuffer video_info,
	RustBuffer progress_watcher,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_send_voice_message(
	void* ptr,
	RustBuffer url,
	RustBuffer audio_info,
	RustBuffer waveform,
	RustBuffer progress_watcher,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_set_name(
	void* ptr,
	RustBuffer name,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_set_topic(
	void* ptr,
	RustBuffer topic,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_subscribe_to_back_pagination_status(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_room_subscribe_to_room_info_updates(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_toggle_reaction(
	void* ptr,
	RustBuffer event_id,
	RustBuffer key,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_room_topic(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_room_upload_avatar(
	void* ptr,
	RustBuffer mime_type,
	RustBuffer data,
	RustBuffer media_info,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roomlist(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlist_entries(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlist_entries_with_dynamic_adapters(
	void* ptr,
	uint32_t page_size,
	uint64_t listener,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlist_loading_state(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlist_room(
	void* ptr,
	RustBuffer room_id,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roomlistdynamicentriescontroller(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_roomlistdynamicentriescontroller_add_one_page(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_roomlistdynamicentriescontroller_reset_to_one_page(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roomlistdynamicentriescontroller_set_filter(
	void* ptr,
	RustBuffer kind,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roomlistitem(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlistitem_avatar_url(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlistitem_canonical_alias(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistitem_full_room(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistitem_full_room_blocking(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roomlistitem_has_unread_notifications(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlistitem_id(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roomlistitem_is_direct(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistitem_latest_event(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roomlistitem_name(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistitem_room_info(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_roomlistitem_subscribe(
	void* ptr,
	RustBuffer settings,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistitem_unread_notifications(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_roomlistitem_unsubscribe(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roomlistservice(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistservice_all_rooms(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistservice_apply_input(
	void* ptr,
	RustBuffer input,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistservice_invites(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistservice_room(
	void* ptr,
	RustBuffer room_id,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistservice_state(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_roomlistservice_sync_indicator(
	void* ptr,
	uint32_t delay_before_showing_in_ms,
	uint32_t delay_before_hiding_in_ms,
	uint64_t listener,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roommember(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roommember_avatar_url(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_ban(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_invite(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_kick(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_redact(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_send_message(
	void* ptr,
	RustBuffer event,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_send_state(
	void* ptr,
	RustBuffer state_event,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_can_trigger_room_notification(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roommember_display_name(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_roommember_ignore(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_is_account_user(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_is_ignored(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_roommember_is_name_ambiguous(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roommember_membership(
	void* ptr,
	RustCallStatus* out_status
);

int64_t uniffi_matrix_sdk_ffi_fn_method_roommember_normalized_power_level(
	void* ptr,
	RustCallStatus* out_status
);

int64_t uniffi_matrix_sdk_ffi_fn_method_roommember_power_level(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_roommember_unignore(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roommember_user_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_roommembersiterator(
	void* ptr,
	RustCallStatus* out_status
);

uint32_t uniffi_matrix_sdk_ffi_fn_method_roommembersiterator_len(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_roommembersiterator_next_chunk(
	void* ptr,
	uint32_t chunk_size,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_sendattachmentjoinhandle(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_sendattachmentjoinhandle_cancel(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sendattachmentjoinhandle_join(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_sessionverificationcontroller(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_approve_verification(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_cancel_verification(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_decline_verification(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_is_verified(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_request_verification(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_set_delegate(
	void* ptr,
	RustBuffer delegate,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_sessionverificationcontroller_start_sas_verification(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_sessionverificationemoji(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_sessionverificationemoji_description(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_sessionverificationemoji_symbol(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_span(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_constructor_span_current(
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_constructor_span_new(
	RustBuffer file,
	RustBuffer line,
	RustBuffer level,
	RustBuffer target,
	RustBuffer name,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_span_enter(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_span_exit(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_span_is_none(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_syncservice(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_syncservice_room_list_service(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_syncservice_start(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_syncservice_state(
	void* ptr,
	uint64_t listener,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_syncservice_stop(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_syncservicebuilder(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_syncservicebuilder_finish(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_syncservicebuilder_with_cross_process_lock(
	void* ptr,
	RustBuffer app_identifier,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_taskhandle(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_method_taskhandle_cancel(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_taskhandle_is_finished(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_timelinediff(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_append(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_change(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_insert(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_push_back(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_push_front(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_remove(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_reset(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelinediff_set(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_timelineevent(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineevent_event_id(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineevent_event_type(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineevent_sender_id(
	void* ptr,
	RustCallStatus* out_status
);

uint64_t uniffi_matrix_sdk_ffi_fn_method_timelineevent_timestamp(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_timelineitem(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineitem_as_event(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineitem_as_virtual(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineitem_fmt_debug(
	void* ptr,
	RustCallStatus* out_status
);

uint64_t uniffi_matrix_sdk_ffi_fn_method_timelineitem_unique_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_timelineitemcontent(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineitemcontent_as_message(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_method_timelineitemcontent_kind(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_unreadnotificationscount(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_matrix_sdk_ffi_fn_method_unreadnotificationscount_has_notifications(
	void* ptr,
	RustCallStatus* out_status
);

uint32_t uniffi_matrix_sdk_ffi_fn_method_unreadnotificationscount_highlight_count(
	void* ptr,
	RustCallStatus* out_status
);

uint32_t uniffi_matrix_sdk_ffi_fn_method_unreadnotificationscount_notification_count(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_widgetdriver(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_widgetdriver_run(
	void* ptr,
	void* room,
	uint64_t capabilities_provider,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_free_widgetdriverhandle(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_widgetdriverhandle_recv(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_method_widgetdriverhandle_send(
	void* ptr,
	RustBuffer msg,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_backpaginationstatuslistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_backupstatelistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_backupsteadystatelistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_clientdelegate(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_clientsessiondelegate(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_enablerecoveryprogresslistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_notificationsettingsdelegate(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_progresswatcher(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_recoverystatelistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_roominfolistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_roomlistentrieslistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_roomlistloadingstatelistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_roomlistservicestatelistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_roomlistservicesyncindicatorlistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_sessionverificationcontrollerdelegate(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_syncservicestateobserver(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_timelinelistener(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_init_callback_widgetcapabilitiesprovider(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_func_gen_transaction_id(
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_generate_webview_url(
	RustBuffer widget_settings,
	void* room,
	RustBuffer props,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_func_get_element_call_required_permissions(
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_func_log_event(
	RustBuffer file,
	RustBuffer line,
	RustBuffer level,
	RustBuffer target,
	RustBuffer message,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_func_make_widget_driver(
	RustBuffer settings,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_media_source_from_url(
	RustBuffer url,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_message_event_content_from_html(
	RustBuffer body,
	RustBuffer html_body,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_message_event_content_from_html_as_emote(
	RustBuffer body,
	RustBuffer html_body,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_message_event_content_from_markdown(
	RustBuffer md,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_message_event_content_from_markdown_as_emote(
	RustBuffer md,
	RustCallStatus* out_status
);

void* uniffi_matrix_sdk_ffi_fn_func_message_event_content_new(
	RustBuffer msgtype,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_func_new_virtual_element_call_widget(
	RustBuffer props,
	RustCallStatus* out_status
);

RustBuffer uniffi_matrix_sdk_ffi_fn_func_sdk_git_sha(
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_func_setup_otlp_tracing(
	RustBuffer config,
	RustCallStatus* out_status
);

void uniffi_matrix_sdk_ffi_fn_func_setup_tracing(
	RustBuffer config,
	RustCallStatus* out_status
);

RustBuffer ffi_matrix_sdk_ffi_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_matrix_sdk_ffi_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_matrix_sdk_ffi_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_matrix_sdk_ffi_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_matrix_sdk_ffi_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_matrix_sdk_ffi_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_matrix_sdk_ffi_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_matrix_sdk_ffi_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_matrix_sdk_ffi_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_matrix_sdk_ffi_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_matrix_sdk_ffi_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_matrix_sdk_ffi_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_matrix_sdk_ffi_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_matrix_sdk_ffi_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_matrix_sdk_ffi_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_matrix_sdk_ffi_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_gen_transaction_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_generate_webview_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_get_element_call_required_permissions(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_log_event(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_make_widget_driver(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_media_source_from_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_message_event_content_from_html(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_message_event_content_from_html_as_emote(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_message_event_content_from_markdown(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_message_event_content_from_markdown_as_emote(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_message_event_content_new(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_new_virtual_element_call_widget(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_sdk_git_sha(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_setup_otlp_tracing(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_func_setup_tracing(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_mediasource_to_json(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_mediasource_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommessageeventcontentwithoutrelation_with_mentions(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_authenticationservice_configure_homeserver(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_authenticationservice_homeserver_details(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_authenticationservice_login(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_authenticationservice_login_with_oidc_callback(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_authenticationservice_url_for_oidc_login(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_account_data(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_account_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_avatar_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_cached_avatar_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_create_room(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_display_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_encryption(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_dm_room(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_media_content(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_media_file(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_media_thumbnail(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_notification_settings(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_profile(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_get_session_verification_controller(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_homeserver(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_ignore_user(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_login(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_logout(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_notification_client(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_remove_avatar(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_restore_session(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_rooms(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_search_users(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_session(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_set_account_data(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_set_delegate(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_set_display_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_set_pusher(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_sync_service(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_unignore_user(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_upload_avatar(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_upload_media(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_client_user_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_base_path(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_build(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_disable_automatic_token_refresh(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_disable_ssl_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_enable_cross_process_refresh_lock(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_homeserver_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_passphrase(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_proxy(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_server_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_server_versions(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_set_session_delegate(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_sliding_sync_proxy(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_user_agent(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientbuilder_username(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_backup_exists_on_server(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_backup_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_backup_state_listener(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_disable_recovery(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_enable_backups(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_enable_recovery(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_fix_recovery_issues(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_is_last_device(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_recover_and_reset(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_recovery_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_recovery_state_listener(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_reset_recovery_key(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_encryption_wait_for_backup_upload_steady_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_can_be_replied_to(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_content(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_debug_info(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_event_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_is_editable(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_is_local(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_is_own(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_is_remote(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_local_send_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_origin(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_reactions(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_read_receipts(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_sender(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_sender_profile(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_timestamp(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_eventtimelineitem_transaction_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_homeserverlogindetails_supports_oidc_login(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_homeserverlogindetails_supports_password_login(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_homeserverlogindetails_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_mediafilehandle_path(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_mediafilehandle_persist(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_message_body(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_message_in_reply_to(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_message_is_edited(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_message_is_threaded(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_message_msgtype(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationclient_get_notification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationclientbuilder_filter_by_push_rules(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationclientbuilder_finish(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_can_homeserver_push_encrypted_event_to_device(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_contains_keywords_rules(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_get_default_room_notification_mode(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_get_room_notification_settings(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_get_rooms_with_user_defined_rules(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_get_user_defined_room_notification_mode(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_is_call_enabled(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_is_room_mention_enabled(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_is_user_mention_enabled(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_restore_default_room_notification_mode(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_set_call_enabled(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_set_default_room_notification_mode(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_set_delegate(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_set_room_mention_enabled(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_set_room_notification_mode(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_set_user_mention_enabled(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettings_unmute_room(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_oidcauthenticationdata_login_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_active_members_count(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_active_room_call_participants(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_add_timeline_listener(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_alternative_aliases(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_avatar_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_ban(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_invite(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_kick(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_redact(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_send_message(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_send_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_can_user_trigger_room_notification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_cancel_send(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_canonical_alias(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_create_poll(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_display_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_edit(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_edit_poll(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_end_poll(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_fetch_details_for_event(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_fetch_members(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_get_event_timeline_item_by_event_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_get_timeline_event_content_by_event_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_has_active_room_call(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_ignore_user(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_invite_user_by_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_invited_members_count(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_inviter(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_is_direct(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_is_encrypted(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_is_public(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_is_space(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_is_tombstoned(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_join(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_joined_members_count(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_leave(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_member(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_member_avatar_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_member_display_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_members(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_membership(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_own_user_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_paginate_backwards(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_redact(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_remove_avatar(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_remove_timeline(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_report_content(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_retry_decryption(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_retry_send(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_room_info(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_audio(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_file(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_image(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_location(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_poll_response(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_read_receipt(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_reply(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_video(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_send_voice_message(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_set_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_set_topic(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_subscribe_to_back_pagination_status(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_subscribe_to_room_info_updates(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_toggle_reaction(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_topic(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_room_upload_avatar(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlist_entries(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlist_entries_with_dynamic_adapters(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlist_loading_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlist_room(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistdynamicentriescontroller_add_one_page(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistdynamicentriescontroller_reset_to_one_page(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistdynamicentriescontroller_set_filter(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_avatar_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_canonical_alias(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_full_room(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_full_room_blocking(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_has_unread_notifications(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_is_direct(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_latest_event(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_room_info(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_subscribe(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_unread_notifications(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistitem_unsubscribe(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservice_all_rooms(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservice_apply_input(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservice_invites(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservice_room(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservice_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservice_sync_indicator(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_avatar_url(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_ban(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_invite(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_kick(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_redact(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_send_message(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_send_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_can_trigger_room_notification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_display_name(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_ignore(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_is_account_user(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_is_ignored(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_is_name_ambiguous(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_membership(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_normalized_power_level(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_power_level(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_unignore(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommember_user_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommembersiterator_len(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roommembersiterator_next_chunk(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sendattachmentjoinhandle_cancel(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sendattachmentjoinhandle_join(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_approve_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_cancel_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_decline_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_is_verified(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_request_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_set_delegate(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontroller_start_sas_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationemoji_description(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationemoji_symbol(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_span_enter(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_span_exit(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_span_is_none(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservice_room_list_service(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservice_start(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservice_state(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservice_stop(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservicebuilder_finish(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservicebuilder_with_cross_process_lock(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_taskhandle_cancel(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_taskhandle_is_finished(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_append(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_change(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_insert(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_push_back(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_push_front(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_remove(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_reset(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinediff_set(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineevent_event_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineevent_event_type(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineevent_sender_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineevent_timestamp(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineitem_as_event(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineitem_as_virtual(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineitem_fmt_debug(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineitem_unique_id(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineitemcontent_as_message(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelineitemcontent_kind(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_unreadnotificationscount_has_notifications(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_unreadnotificationscount_highlight_count(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_unreadnotificationscount_notification_count(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_widgetdriver_run(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_widgetdriverhandle_recv(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_widgetdriverhandle_send(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_constructor_mediasource_from_json(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_constructor_authenticationservice_new(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_constructor_clientbuilder_new(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_constructor_span_current(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_constructor_span_new(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_backpaginationstatuslistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_backupstatelistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_backupsteadystatelistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientdelegate_did_receive_auth_error(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientdelegate_did_refresh_tokens(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientsessiondelegate_retrieve_session_from_keychain(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_clientsessiondelegate_save_session_in_keychain(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_enablerecoveryprogresslistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_notificationsettingsdelegate_settings_did_change(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_progresswatcher_transmission_progress(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_recoverystatelistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roominfolistener_call(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistentrieslistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistloadingstatelistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservicestatelistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_roomlistservicesyncindicatorlistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontrollerdelegate_did_accept_verification_request(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontrollerdelegate_did_start_sas_verification(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontrollerdelegate_did_receive_verification_data(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontrollerdelegate_did_fail(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontrollerdelegate_did_cancel(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_sessionverificationcontrollerdelegate_did_finish(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_syncservicestateobserver_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_timelinelistener_on_update(
	RustCallStatus* out_status
);

uint16_t uniffi_matrix_sdk_ffi_checksum_method_widgetcapabilitiesprovider_acquire_capabilities(
	RustCallStatus* out_status
);

uint32_t ffi_matrix_sdk_ffi_uniffi_contract_version(
	RustCallStatus* out_status
);


int32_t matrix_sdk_ffi_cgo_BackPaginationStatusListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_BackupStateListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_BackupSteadyStateListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_ClientDelegate(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_ClientSessionDelegate(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_EnableRecoveryProgressListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_NotificationSettingsDelegate(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_ProgressWatcher(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_RecoveryStateListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_RoomInfoListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_RoomListEntriesListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_RoomListLoadingStateListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_RoomListServiceStateListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_RoomListServiceSyncIndicatorListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_SessionVerificationControllerDelegate(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_SyncServiceStateObserver(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_TimelineListener(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t matrix_sdk_ffi_cgo_WidgetCapabilitiesProvider(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

